sudo: false
language: java
jdk:
  - oraclejdk7
script:
  - mvn clean install
  - jdk_switcher use oraclejdk8
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.login=$SONAR_TOKEN
